### ISSUE TITLE
Hoola, hola! Probando, probando.... jeje!!

### ISSUE THREAD

**Issue by GabrielAguilar2023** [Blue22Feather/Iguazu-Capibara__Page#1]
Les pregunto... Para una mejor organzacion de las ramas.... Les parece que usemos una estructura como la de GitFlow?

https://i0.wp.com/select2web.com/wp-content/uploads/git-workflow-release-cycle-4maintenance.png?w=614&ssl=1

donde cada uno trabaja a nivel de _**feature**_ (por ejemplo, diseño de index, o... efectos de transision... o procesamiento de reservas...) y despues vamos integrando hacia abajo a _**develop**_ y lo que vaya funcionando lo vamos _mergeando_ y va quedando... despues una vez terminada la tarea... se sube a **_develop_** y se borra la rama feature que se subio... se busca otra tares, se crea otra ramas de _nueva feature_ a partir de **_develop_**... y asi, se va bajando y filtrando... se entiende? Asi lo que va andando no se toca y siempre se trabaja sobre mejoras o adiciones... y los conflictos entre codigos no afecta a lo que ya ha ido aprobando....

**Comment by GabrielAguilar2023** [comment]
O si les parece muy elaborado... cada uno hace una rama y listo... Tampoco es para complicarse la vida.. jeje!

**Comment by Blue22Feather** [comment]
no te entendi mucho; supongo que dices ir creando ramas a medida y crear copias de seguridad como si fuera otra rama? ahorita hay 3 ramas; main, system e interface; borro las dos extras y copiamos el main y de alli trabajamos la primera parte dices?

**Comment by GabrielAguilar2023** [comment]
Claro... las ramas deberian salir del mismo ancestro en comun, sino despues va a haber problemas de union de codigo...Por eso nuestras ramas deberian hacerse en base a una rama comun (no main) porque si no se puede arreglar el conflicto de ramas, hay que borrarla y no nos gustaria borrar el main... Pero este proyecto es chico y creo que no habria grandes problemas.... si queremos seguirlo trabajando asi con las ramas que estan... No hay problemas de mi parte.

**Comment by Blue22Feather** [comment]
a ver... tienes otra forma de explicar que chuchas son los workflows?

**Comment by LaPiragna** [comment]
Entiendo que workflow sería cómo se organiza un equipo con respecto a las ramas.

**Comment by GabrielAguilar2023** [comment]
El **Git Flow** es un modelo de implementacion. Es una recomendacion  a cerca de como organizar las ramas para un funcionamiento con menos conflictos... Hay varias _"branching strategies"_, pero la mas adecuada para nuestro caso considero que es esta. No es que **se necesite hacerlo**. Pero sí, está bueno que se vayan acostumbrando al concepto ya que es ampliamente usado en los desarrollos colaborativos... Acá les dejo un videito que lo explica un poco.. 

https://www.youtube.com/watch?v=atYIzPIeeQk

Pero les repito, no es necesrio... si no estan acostumbrados o no les parece, no se compliquen y sigamos con las ramas que estan. Era sólo una idea.
